# permissions for end users to edit ballistaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ballistacluster-editor-role
rules:
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters/status
  verbs:
  - get
