# permissions for end users to view ballistaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ballistacluster-viewer-role
rules:
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters/status
  verbs:
  - get
