
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ballista.minzhou.info
  resources:
  - ballistaclusters/status
  verbs:
  - get
  - patch
  - update
